///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace PRJ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the PRJRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("710f379c-4131-4f1c-87bf-6ea03949c1a4")]
    public partial class PRJRepository : RepoGenBaseFolder
    {
        static PRJRepository instance = new PRJRepository();
        PRJRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        PRJRepositoryFolders.DropdownAppFolder _dropdown;
        PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışveAppFolder _gittigidiyortuerkiyeninoencuealışve;
        PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışve1AppFolder _gittigidiyortuerkiyeninoencuealışve1;
        PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışve2AppFolder _gittigidiyortuerkiyeninoencuealışve2;
        PRJRepositoryFolders.GittiGidiyorYardımSayfalarınaHoşgeldiAppFolder _gittigidiyoryardımsayfalarınahoşgeldi;

        /// <summary>
        /// Gets the singleton class instance representing the PRJRepository element repository.
        /// </summary>
        [RepositoryFolder("710f379c-4131-4f1c-87bf-6ea03949c1a4")]
        public static PRJRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public PRJRepository() 
            : base("PRJRepository", "/", null, 0, false, "710f379c-4131-4f1c-87bf-6ea03949c1a4", ".\\RepositoryImages\\PRJRepository710f379c.rximgres")
        {
            _applicationundertest = new PRJRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _dropdown = new PRJRepositoryFolders.DropdownAppFolder(this);
            _gittigidiyortuerkiyeninoencuealışve = new PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışveAppFolder(this);
            _gittigidiyortuerkiyeninoencuealışve1 = new PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışve1AppFolder(this);
            _gittigidiyortuerkiyeninoencuealışve2 = new PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışve2AppFolder(this);
            _gittigidiyoryardımsayfalarınahoşgeldi = new PRJRepositoryFolders.GittiGidiyorYardımSayfalarınaHoşgeldiAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("710f379c-4131-4f1c-87bf-6ea03949c1a4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("5bea6234-e11f-418a-aea7-8876489c739b")]
        public virtual PRJRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("16356e4f-f4cf-480c-a32d-641f9c650839")]
        public virtual PRJRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The GittiGidiyorTuerkiyeninOEncueAlışve folder.
        /// </summary>
        [RepositoryFolder("76cbb887-abcd-462c-b806-56288b24be86")]
        public virtual PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışveAppFolder GittiGidiyorTuerkiyeninOEncueAlışve
        {
            get { return _gittigidiyortuerkiyeninoencuealışve; }
        }

        /// <summary>
        /// The GittiGidiyorTuerkiyeninOEncueAlışve1 folder.
        /// </summary>
        [RepositoryFolder("ec9a252d-0c03-4511-a8bb-33804167abb6")]
        public virtual PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışve1AppFolder GittiGidiyorTuerkiyeninOEncueAlışve1
        {
            get { return _gittigidiyortuerkiyeninoencuealışve1; }
        }

        /// <summary>
        /// The GittiGidiyorTuerkiyeninOEncueAlışve2 folder.
        /// </summary>
        [RepositoryFolder("b5e8af47-5b31-4617-8936-19add35394e2")]
        public virtual PRJRepositoryFolders.GittiGidiyorTuerkiyeninOEncueAlışve2AppFolder GittiGidiyorTuerkiyeninOEncueAlışve2
        {
            get { return _gittigidiyortuerkiyeninoencuealışve2; }
        }

        /// <summary>
        /// The GittiGidiyorYardımSayfalarınaHoşgeldi folder.
        /// </summary>
        [RepositoryFolder("07a80ede-b8ae-4bf6-b8f8-f96872a27f78")]
        public virtual PRJRepositoryFolders.GittiGidiyorYardımSayfalarınaHoşgeldiAppFolder GittiGidiyorYardımSayfalarınaHoşgeldi
        {
            get { return _gittigidiyoryardımsayfalarınahoşgeldi; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class PRJRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("5bea6234-e11f-418a-aea7-8876489c739b")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            PRJRepositoryFolders.RegisterPostFolder _registerpost;
            RepoItemInfo _suggestionemailinputverifierInfo;
            RepoItemInfo _pwdfieldInfo;
            RepoItemInfo _containerInfo;
            RepoItemInfo _gsmdataInfo;
            RepoItemInfo _submitformInfo;
            RepoItemInfo _sepeteekleInfo;
            RepoItemInfo _sepeteekle1Info;
            RepoItemInfo _sepetimInfo;
            RepoItemInfo _addproduct1Info;
            RepoItemInfo _addproduct2Info;
            RepoItemInfo _myaccount_favouritesInfo;
            RepoItemInfo _logoutInfo;
            RepoItemInfo _sepetim1Info;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.gittigidiyor.com']//header[#'main-header']/div[3]/div/div/div/div[2]/form[@action='https://www.gittigidiyor.com/arama/']//button/span[@innertext='BUL']", parentFolder, 30000, null, false, "5bea6234-e11f-418a-aea7-8876489c739b", "")
            {
                _registerpost = new PRJRepositoryFolders.RegisterPostFolder(this);
                _suggestionemailinputverifierInfo = new RepoItemInfo(this, "SuggestionEmailInputVerifier", ".//input[#'suggestion_email_input_verifier']", "", 30000, null, "ad9ddb13-0003-401a-ae14-618891bd2eee");
                _pwdfieldInfo = new RepoItemInfo(this, "PwdField", ".//input[#'pwdField']", "", 30000, null, "e5909999-640d-460c-9477-17dbf4e11275");
                _containerInfo = new RepoItemInfo(this, "Container", ".//div[#'MainContainer']/div[3]/div[1]", "", 30000, null, "7518e340-c8d6-4362-8449-3eb8fe42f7bb");
                _gsmdataInfo = new RepoItemInfo(this, "GsmData", ".//input[#'gsmData']", "", 30000, null, "c2a04d02-d104-4486-acea-e0873b7a7d39");
                _submitformInfo = new RepoItemInfo(this, "SubmitForm", "descendant-or-self::*/input[#'SubmitForm']", "", 30000, null, "4f80534b-85ce-4cf5-b645-bdcd959713a8");
                _sepeteekleInfo = new RepoItemInfo(this, "SepeteEkle", ".//div[7]/article/div//span[@innertext='Sepete Ekle']", "", 30000, null, "8c93f2c9-f498-4810-92cc-7f67ff43af73");
                _sepeteekle1Info = new RepoItemInfo(this, "SepeteEkle1", ".//div[8]/article//span[@innertext='Sepete Ekle']", "", 30000, null, "b9f5f84d-cb57-408b-a9ff-d14bb289ab3e");
                _sepetimInfo = new RepoItemInfo(this, "Sepetim", ".//header[#'main-header']/div[3]/div/div/div/div[3]//a[@title='Sepetim']/div[@title='Sepetim']/div[@innertext='Sepetim']", "", 30000, null, "95dfb226-3001-4070-9ef1-58e31cf638aa");
                _addproduct1Info = new RepoItemInfo(this, "AddProduct1", ".//div[#'__next']/main/div[2]/div[3]/div/div[2]/div/div[3]/div[3]/ul/li[1]/article//svg", "", 30000, null, "e11d9587-b622-4ed3-b891-06761da8463d");
                _addproduct2Info = new RepoItemInfo(this, "AddProduct2", ".//div[#'__next']/main/div[2]/div[3]/div/div[2]/div/div[3]/div[3]/ul/li[2]/article//svg", "li[2]/article/div[1]/div/svg", 30000, null, "1b284ca8-2747-4e4c-89a1-59814c0ae7db");
                _myaccount_favouritesInfo = new RepoItemInfo(this, "MyAccount_Favourites", ".//header[#'main-header']/div[4]/div/div/div/div[3]/div/div[2]", "", 30000, null, "dd49a5ca-65db-4338-8947-77519c1a7834");
                _logoutInfo = new RepoItemInfo(this, "Logout", ".//header[#'main-header']/div[4]/div/div/div/div[3]/div/div[2]", "", 30000, null, "da030965-e589-48c0-8cbf-51253c5a6b8e");
                _sepetim1Info = new RepoItemInfo(this, "Sepetim1", ".//header[#'main-header']/div[3]/div/div/div/div[3]//a[@title='Sepetim']/div[@title='Sepetim']/div[@innertext='Sepetim']", "", 30000, null, "11e371c5-bb12-4e6c-b4b3-af3a2234459c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5bea6234-e11f-418a-aea7-8876489c739b")]
            public virtual Ranorex.SpanTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5bea6234-e11f-418a-aea7-8876489c739b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SuggestionEmailInputVerifier item.
            /// </summary>
            [RepositoryItem("ad9ddb13-0003-401a-ae14-618891bd2eee")]
            public virtual Ranorex.InputTag SuggestionEmailInputVerifier
            {
                get
                {
                    return _suggestionemailinputverifierInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SuggestionEmailInputVerifier item info.
            /// </summary>
            [RepositoryItemInfo("ad9ddb13-0003-401a-ae14-618891bd2eee")]
            public virtual RepoItemInfo SuggestionEmailInputVerifierInfo
            {
                get
                {
                    return _suggestionemailinputverifierInfo;
                }
            }

            /// <summary>
            /// The PwdField item.
            /// </summary>
            [RepositoryItem("e5909999-640d-460c-9477-17dbf4e11275")]
            public virtual Ranorex.InputTag PwdField
            {
                get
                {
                    return _pwdfieldInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PwdField item info.
            /// </summary>
            [RepositoryItemInfo("e5909999-640d-460c-9477-17dbf4e11275")]
            public virtual RepoItemInfo PwdFieldInfo
            {
                get
                {
                    return _pwdfieldInfo;
                }
            }

            /// <summary>
            /// The Container item.
            /// </summary>
            [RepositoryItem("7518e340-c8d6-4362-8449-3eb8fe42f7bb")]
            public virtual Ranorex.DivTag Container
            {
                get
                {
                    return _containerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Container item info.
            /// </summary>
            [RepositoryItemInfo("7518e340-c8d6-4362-8449-3eb8fe42f7bb")]
            public virtual RepoItemInfo ContainerInfo
            {
                get
                {
                    return _containerInfo;
                }
            }

            /// <summary>
            /// The GsmData item.
            /// </summary>
            [RepositoryItem("c2a04d02-d104-4486-acea-e0873b7a7d39")]
            public virtual Ranorex.InputTag GsmData
            {
                get
                {
                    return _gsmdataInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GsmData item info.
            /// </summary>
            [RepositoryItemInfo("c2a04d02-d104-4486-acea-e0873b7a7d39")]
            public virtual RepoItemInfo GsmDataInfo
            {
                get
                {
                    return _gsmdataInfo;
                }
            }

            /// <summary>
            /// The SubmitForm item.
            /// </summary>
            [RepositoryItem("4f80534b-85ce-4cf5-b645-bdcd959713a8")]
            public virtual Ranorex.InputTag SubmitForm
            {
                get
                {
                    return _submitformInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitForm item info.
            /// </summary>
            [RepositoryItemInfo("4f80534b-85ce-4cf5-b645-bdcd959713a8")]
            public virtual RepoItemInfo SubmitFormInfo
            {
                get
                {
                    return _submitformInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle item.
            /// </summary>
            [RepositoryItem("8c93f2c9-f498-4810-92cc-7f67ff43af73")]
            public virtual Ranorex.SpanTag SepeteEkle
            {
                get
                {
                    return _sepeteekleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle item info.
            /// </summary>
            [RepositoryItemInfo("8c93f2c9-f498-4810-92cc-7f67ff43af73")]
            public virtual RepoItemInfo SepeteEkleInfo
            {
                get
                {
                    return _sepeteekleInfo;
                }
            }

            /// <summary>
            /// The SepeteEkle1 item.
            /// </summary>
            [RepositoryItem("b9f5f84d-cb57-408b-a9ff-d14bb289ab3e")]
            public virtual Ranorex.SpanTag SepeteEkle1
            {
                get
                {
                    return _sepeteekle1Info.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SepeteEkle1 item info.
            /// </summary>
            [RepositoryItemInfo("b9f5f84d-cb57-408b-a9ff-d14bb289ab3e")]
            public virtual RepoItemInfo SepeteEkle1Info
            {
                get
                {
                    return _sepeteekle1Info;
                }
            }

            /// <summary>
            /// The Sepetim item.
            /// </summary>
            [RepositoryItem("95dfb226-3001-4070-9ef1-58e31cf638aa")]
            public virtual Ranorex.DivTag Sepetim
            {
                get
                {
                    return _sepetimInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim item info.
            /// </summary>
            [RepositoryItemInfo("95dfb226-3001-4070-9ef1-58e31cf638aa")]
            public virtual RepoItemInfo SepetimInfo
            {
                get
                {
                    return _sepetimInfo;
                }
            }

            /// <summary>
            /// The AddProduct1 item.
            /// </summary>
            [RepositoryItem("e11d9587-b622-4ed3-b891-06761da8463d")]
            public virtual Ranorex.SvgTag AddProduct1
            {
                get
                {
                    return _addproduct1Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The AddProduct1 item info.
            /// </summary>
            [RepositoryItemInfo("e11d9587-b622-4ed3-b891-06761da8463d")]
            public virtual RepoItemInfo AddProduct1Info
            {
                get
                {
                    return _addproduct1Info;
                }
            }

            /// <summary>
            /// The AddProduct2 item.
            /// </summary>
            [RepositoryItem("1b284ca8-2747-4e4c-89a1-59814c0ae7db")]
            public virtual Ranorex.SvgTag AddProduct2
            {
                get
                {
                    return _addproduct2Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The AddProduct2 item info.
            /// </summary>
            [RepositoryItemInfo("1b284ca8-2747-4e4c-89a1-59814c0ae7db")]
            public virtual RepoItemInfo AddProduct2Info
            {
                get
                {
                    return _addproduct2Info;
                }
            }

            /// <summary>
            /// The MyAccount_Favourites item.
            /// </summary>
            [RepositoryItem("dd49a5ca-65db-4338-8947-77519c1a7834")]
            public virtual Ranorex.DivTag MyAccount_Favourites
            {
                get
                {
                    return _myaccount_favouritesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The MyAccount_Favourites item info.
            /// </summary>
            [RepositoryItemInfo("dd49a5ca-65db-4338-8947-77519c1a7834")]
            public virtual RepoItemInfo MyAccount_FavouritesInfo
            {
                get
                {
                    return _myaccount_favouritesInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("da030965-e589-48c0-8cbf-51253c5a6b8e")]
            public virtual Ranorex.DivTag Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("da030965-e589-48c0-8cbf-51253c5a6b8e")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The Sepetim1 item.
            /// </summary>
            [RepositoryItem("11e371c5-bb12-4e6c-b4b3-af3a2234459c")]
            public virtual Ranorex.DivTag Sepetim1
            {
                get
                {
                    return _sepetim1Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Sepetim1 item info.
            /// </summary>
            [RepositoryItemInfo("11e371c5-bb12-4e6c-b4b3-af3a2234459c")]
            public virtual RepoItemInfo Sepetim1Info
            {
                get
                {
                    return _sepetim1Info;
                }
            }

            /// <summary>
            /// The RegisterPost folder.
            /// </summary>
            [RepositoryFolder("cf98228b-44d0-48c6-93ee-ca1a0f887895")]
            public virtual PRJRepositoryFolders.RegisterPostFolder RegisterPost
            {
                get { return _registerpost; }
            }
        }

        /// <summary>
        /// The RegisterPostFolder folder.
        /// </summary>
        [RepositoryFolder("cf98228b-44d0-48c6-93ee-ca1a0f887895")]
        public partial class RegisterPostFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nameInfo;
            RepoItemInfo _surnameInfo;
            RepoItemInfo _checkmarkInfo;

            /// <summary>
            /// Creates a new RegisterPost  folder.
            /// </summary>
            public RegisterPostFolder(RepoGenBaseFolder parentFolder) :
                    base("RegisterPost", ".//form[#'RegisterPost']", parentFolder, 30000, null, false, "cf98228b-44d0-48c6-93ee-ca1a0f887895", "")
            {
                _nameInfo = new RepoItemInfo(this, "Name", "div/div/?/?/div[@innertext='Adınız*']", "", 30000, null, "8970a133-adf0-460d-8633-5ae41c548312");
                _surnameInfo = new RepoItemInfo(this, "Surname", "div/div/?/?/div[@innertext='Soyadınız*']", "", 30000, null, "f0681014-ca8d-4f15-a88c-12ad95c8e082");
                _checkmarkInfo = new RepoItemInfo(this, "Checkmark", "div[8]//label/span[1]", "", 30000, null, "6b584b49-572e-488a-8142-5ad749543069");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cf98228b-44d0-48c6-93ee-ca1a0f887895")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cf98228b-44d0-48c6-93ee-ca1a0f887895")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("8970a133-adf0-460d-8633-5ae41c548312")]
            public virtual Ranorex.DivTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("8970a133-adf0-460d-8633-5ae41c548312")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Surname item.
            /// </summary>
            [RepositoryItem("f0681014-ca8d-4f15-a88c-12ad95c8e082")]
            public virtual Ranorex.DivTag Surname
            {
                get
                {
                    return _surnameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Surname item info.
            /// </summary>
            [RepositoryItemInfo("f0681014-ca8d-4f15-a88c-12ad95c8e082")]
            public virtual RepoItemInfo SurnameInfo
            {
                get
                {
                    return _surnameInfo;
                }
            }

            /// <summary>
            /// The Checkmark item.
            /// </summary>
            [RepositoryItem("6b584b49-572e-488a-8142-5ad749543069")]
            public virtual Ranorex.SpanTag Checkmark
            {
                get
                {
                    return _checkmarkInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Checkmark item info.
            /// </summary>
            [RepositoryItemInfo("6b584b49-572e-488a-8142-5ad749543069")]
            public virtual RepoItemInfo CheckmarkInfo
            {
                get
                {
                    return _checkmarkInfo;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("16356e4f-f4cf-480c-a32d-641f9c650839")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _submitInfo;
            RepoItemInfo _inputtagkInfo;
            RepoItemInfo _searchInfo;
            RepoItemInfo _nameInfo;
            RepoItemInfo _surnameInfo;

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container", parentFolder, 30000, null, true, "16356e4f-f4cf-480c-a32d-641f9c650839", "")
            {
                _submitInfo = new RepoItemInfo(this, "Submit", ".//input[@type='submit']", "", 30000, null, "8b279542-f0f1-4136-aa1a-39f173085e45");
                _inputtagkInfo = new RepoItemInfo(this, "InputTagK", ".//header[#'main-header']/div[3]/div/div/div/div[2]/form[@action='https://www.gittigidiyor.com/arama/']/div/div[1]/?/?/input[@name='k']", "", 30000, null, "5ea63a2f-0998-4e90-b728-2dd27fa5acf5");
                _searchInfo = new RepoItemInfo(this, "Search", ".//header[#'main-header']/div[3]/div/div/div/div[2]/form[@action='https://www.gittigidiyor.com/arama/']//button", ".//header[#'main-header']//button", 30000, null, "dfde16d4-8b95-457a-acb0-019c18ba4676");
                _nameInfo = new RepoItemInfo(this, "Name", ".//form[#'RegisterPost']/div[2]//input[@name='name']", ".//form[#'RegisterPost']//input[@name='name']", 30000, null, "b77c762e-8ac7-4fe5-bcd4-767f9b8d3ed1");
                _surnameInfo = new RepoItemInfo(this, "Surname", ".//form[#'RegisterPost']/div[3]//input[@name='surname']", ".//form[#'RegisterPost']//input[@name='surname']", 30000, null, "3ad08500-1b1e-44b9-ba51-26f33921b4e8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("16356e4f-f4cf-480c-a32d-641f9c650839")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("16356e4f-f4cf-480c-a32d-641f9c650839")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("8b279542-f0f1-4136-aa1a-39f173085e45")]
            public virtual Ranorex.InputTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("8b279542-f0f1-4136-aa1a-39f173085e45")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The InputTagK item.
            /// </summary>
            [RepositoryItem("5ea63a2f-0998-4e90-b728-2dd27fa5acf5")]
            public virtual Ranorex.InputTag InputTagK
            {
                get
                {
                    return _inputtagkInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagK item info.
            /// </summary>
            [RepositoryItemInfo("5ea63a2f-0998-4e90-b728-2dd27fa5acf5")]
            public virtual RepoItemInfo InputTagKInfo
            {
                get
                {
                    return _inputtagkInfo;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("dfde16d4-8b95-457a-acb0-019c18ba4676")]
            public virtual Ranorex.ButtonTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("dfde16d4-8b95-457a-acb0-019c18ba4676")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The Name item.
            /// </summary>
            [RepositoryItem("b77c762e-8ac7-4fe5-bcd4-767f9b8d3ed1")]
            public virtual Ranorex.InputTag Name
            {
                get
                {
                    return _nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Name item info.
            /// </summary>
            [RepositoryItemInfo("b77c762e-8ac7-4fe5-bcd4-767f9b8d3ed1")]
            public virtual RepoItemInfo NameInfo
            {
                get
                {
                    return _nameInfo;
                }
            }

            /// <summary>
            /// The Surname item.
            /// </summary>
            [RepositoryItem("3ad08500-1b1e-44b9-ba51-26f33921b4e8")]
            public virtual Ranorex.InputTag Surname
            {
                get
                {
                    return _surnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Surname item info.
            /// </summary>
            [RepositoryItemInfo("3ad08500-1b1e-44b9-ba51-26f33921b4e8")]
            public virtual RepoItemInfo SurnameInfo
            {
                get
                {
                    return _surnameInfo;
                }
            }
        }

        /// <summary>
        /// The GittiGidiyorTuerkiyeninOEncueAlışveAppFolder folder.
        /// </summary>
        [RepositoryFolder("76cbb887-abcd-462c-b806-56288b24be86")]
        public partial class GittiGidiyorTuerkiyeninOEncueAlışveAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _spantagbulInfo;
            RepoItemInfo _addtobasketInfo;

            /// <summary>
            /// Creates a new GittiGidiyorTuerkiyeninOEncueAlışve  folder.
            /// </summary>
            public GittiGidiyorTuerkiyeninOEncueAlışveAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GittiGidiyorTuerkiyeninOEncueAlışve", "/dom[@domain='www.gittigidiyor.com']//div[#'__next']/main/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/ul/li[1]/article/?/?/a[@title>'Insiginia 4GB+64GB 8 Çekirdek']//img[@alt>'Insiginia 4GB+64GB 8 Çekirdek']", parentFolder, 30000, null, false, "76cbb887-abcd-462c-b806-56288b24be86", "")
            {
                _spantagbulInfo = new RepoItemInfo(this, "SpanTagBUL", ".//header[#'main-header']/div[3]/div/div/div/div[2]/form[@action='https://www.gittigidiyor.com/arama/']//button/span[@innertext='BUL']", "", 30000, null, "789fbf2c-a89d-4d83-b767-7638a357f69f");
                _addtobasketInfo = new RepoItemInfo(this, "AddToBasket", ".//button[#'add-to-basket']", "", 30000, null, "829b14dd-000e-4219-b590-f0345fdc688a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("76cbb887-abcd-462c-b806-56288b24be86")]
            public virtual Ranorex.ImgTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("76cbb887-abcd-462c-b806-56288b24be86")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SpanTagBUL item.
            /// </summary>
            [RepositoryItem("789fbf2c-a89d-4d83-b767-7638a357f69f")]
            public virtual Ranorex.SpanTag SpanTagBUL
            {
                get
                {
                    return _spantagbulInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagBUL item info.
            /// </summary>
            [RepositoryItemInfo("789fbf2c-a89d-4d83-b767-7638a357f69f")]
            public virtual RepoItemInfo SpanTagBULInfo
            {
                get
                {
                    return _spantagbulInfo;
                }
            }

            /// <summary>
            /// The AddToBasket item.
            /// </summary>
            [RepositoryItem("829b14dd-000e-4219-b590-f0345fdc688a")]
            public virtual Ranorex.ButtonTag AddToBasket
            {
                get
                {
                    return _addtobasketInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToBasket item info.
            /// </summary>
            [RepositoryItemInfo("829b14dd-000e-4219-b590-f0345fdc688a")]
            public virtual RepoItemInfo AddToBasketInfo
            {
                get
                {
                    return _addtobasketInfo;
                }
            }
        }

        /// <summary>
        /// The GittiGidiyorTuerkiyeninOEncueAlışve1AppFolder folder.
        /// </summary>
        [RepositoryFolder("ec9a252d-0c03-4511-a8bb-33804167abb6")]
        public partial class GittiGidiyorTuerkiyeninOEncueAlışve1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _f2r72j3jndvfbInfo;
            RepoItemInfo _addtobasketInfo;
            RepoItemInfo _httpswwwgittigidiyorcomsepetimInfo;

            /// <summary>
            /// Creates a new GittiGidiyorTuerkiyeninOEncueAlışve1  folder.
            /// </summary>
            public GittiGidiyorTuerkiyeninOEncueAlışve1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GittiGidiyorTuerkiyeninOEncueAlışve1", "/dom[@domain='www.gittigidiyor.com']//div[#'__next']/main/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/ul/li[1]/article/?/?/a[@title='Oppo A74 128 GB Siyah']//header/?/?/h2[@title='Oppo A74 128 GB Siyah']", parentFolder, 30000, null, false, "ec9a252d-0c03-4511-a8bb-33804167abb6", "")
            {
                _f2r72j3jndvfbInfo = new RepoItemInfo(this, "F2r72j3JNDvfB", ".//header[#'main-header']/div[4]/div//nav", "", 30000, null, "21edaa5a-1ca1-4aeb-9b7f-a7564bbb9dcc");
                _addtobasketInfo = new RepoItemInfo(this, "AddToBasket", ".//button[#'add-to-basket']", "", 30000, null, "bb50b27a-1f29-42c5-8dda-032658e9f0db");
                _httpswwwgittigidiyorcomsepetimInfo = new RepoItemInfo(this, "HttpsWwwGittigidiyorComSepetim", ".//div[#'header_wrapper']/div[4]/div[3]/div/a[@href>'https://www.gittigidiyor.']", "", 30000, null, "eaf14ff6-a7bb-4d5d-8be3-2cd95d780d3a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ec9a252d-0c03-4511-a8bb-33804167abb6")]
            public virtual Ranorex.H2Tag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ec9a252d-0c03-4511-a8bb-33804167abb6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The F2r72j3JNDvfB item.
            /// </summary>
            [RepositoryItem("21edaa5a-1ca1-4aeb-9b7f-a7564bbb9dcc")]
            public virtual Ranorex.NavTag F2r72j3JNDvfB
            {
                get
                {
                    return _f2r72j3jndvfbInfo.CreateAdapter<Ranorex.NavTag>(true);
                }
            }

            /// <summary>
            /// The F2r72j3JNDvfB item info.
            /// </summary>
            [RepositoryItemInfo("21edaa5a-1ca1-4aeb-9b7f-a7564bbb9dcc")]
            public virtual RepoItemInfo F2r72j3JNDvfBInfo
            {
                get
                {
                    return _f2r72j3jndvfbInfo;
                }
            }

            /// <summary>
            /// The AddToBasket item.
            /// </summary>
            [RepositoryItem("bb50b27a-1f29-42c5-8dda-032658e9f0db")]
            public virtual Ranorex.ButtonTag AddToBasket
            {
                get
                {
                    return _addtobasketInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToBasket item info.
            /// </summary>
            [RepositoryItemInfo("bb50b27a-1f29-42c5-8dda-032658e9f0db")]
            public virtual RepoItemInfo AddToBasketInfo
            {
                get
                {
                    return _addtobasketInfo;
                }
            }

            /// <summary>
            /// The HttpsWwwGittigidiyorComSepetim item.
            /// </summary>
            [RepositoryItem("eaf14ff6-a7bb-4d5d-8be3-2cd95d780d3a")]
            public virtual Ranorex.ATag HttpsWwwGittigidiyorComSepetim
            {
                get
                {
                    return _httpswwwgittigidiyorcomsepetimInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HttpsWwwGittigidiyorComSepetim item info.
            /// </summary>
            [RepositoryItemInfo("eaf14ff6-a7bb-4d5d-8be3-2cd95d780d3a")]
            public virtual RepoItemInfo HttpsWwwGittigidiyorComSepetimInfo
            {
                get
                {
                    return _httpswwwgittigidiyorcomsepetimInfo;
                }
            }
        }

        /// <summary>
        /// The GittiGidiyorTuerkiyeninOEncueAlışve2AppFolder folder.
        /// </summary>
        [RepositoryFolder("b5e8af47-5b31-4617-8936-19add35394e2")]
        public partial class GittiGidiyorTuerkiyeninOEncueAlışve2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _xiaomiredmi9t64gbxiaomituerkiyegInfo;
            RepoItemInfo _sueperfiyatlarInfo;
            RepoItemInfo _walkingpadr1pro125hpkatlanabilirkInfo;
            RepoItemInfo _addtobasketInfo;
            RepoItemInfo _spantagbulInfo;
            RepoItemInfo _appleiphone13512gbappletuerkiyegaInfo;
            RepoItemInfo _somesvgtagInfo;
            RepoItemInfo _somesvgtag1Info;

            /// <summary>
            /// Creates a new GittiGidiyorTuerkiyeninOEncueAlışve2  folder.
            /// </summary>
            public GittiGidiyorTuerkiyeninOEncueAlışve2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GittiGidiyorTuerkiyeninOEncueAlışve2", "/dom[@domain='www.gittigidiyor.com']", parentFolder, 30000, null, false, "b5e8af47-5b31-4617-8936-19add35394e2", "")
            {
                _xiaomiredmi9t64gbxiaomituerkiyegInfo = new RepoItemInfo(this, "XiaomiRedmi9T64GBXiaomiTuerkiyeG", ".//div[#'__next']/main/div/div/section[5]/section/div/div/div/div/div/div/div[2]/div[1]/div[7]/article/?/?/a[@title>'Xiaomi Redmi 9T 64 GB (Xiaomi']/div/div[2]/header/?/?/h2[@title>'Xiaomi Redmi 9T 64 GB (Xiaomi']", "", 30000, null, "ac0bed3c-64d9-4e18-85c7-fceea316ddf5");
                _sueperfiyatlarInfo = new RepoItemInfo(this, "SueperFiyatlar", ".//div[#'HeaderLinkContainer']/a[@innertext='Süper Fiyatlar']", ".//div[#'HeaderLinkContainer']/a[@innertext='Süper Fiyatlar']", 30000, null, "eb4c045a-a353-4dcb-95ae-e6fd3877c463");
                _walkingpadr1pro125hpkatlanabilirkInfo = new RepoItemInfo(this, "WalkingpadR1Pro125HpKatlanabilirK", ".//div[#'__next']/main/div[2]/div[2]/div/div[2]/div/div/div[2]/ul/li[1]/article/?/?/a[@title>'Walkingpad R1 Pro 1.25 Hp']//header/?/?/h2[@title>'Walkingpad R1 Pro 1.25 Hp']", ".//div[#'__next']//h2[@title>'Walkingpad R1 Pro 1.25 Hp']", 30000, null, "2190d1b8-ec2b-4a3e-8b4b-ce7f88a7bb70");
                _addtobasketInfo = new RepoItemInfo(this, "AddToBasket", ".//button[#'add-to-basket']", "", 30000, null, "b80ece62-c474-4d9a-b7f9-854b8281a833");
                _spantagbulInfo = new RepoItemInfo(this, "SpanTagBUL", ".//header[#'main-header']/div[3]/div/div/div/div[2]/form[@action='https://www.gittigidiyor.com/arama/']//button/span[@innertext='BUL']", ".//header[#'main-header']//span[@innertext='BUL']", 30000, null, "cea0bca2-6c88-431c-b4d8-e14fb7ac7b65");
                _appleiphone13512gbappletuerkiyegaInfo = new RepoItemInfo(this, "AppleIPhone13512GBAppleTuerkiyeGa", ".//div[#'__next']/main/div[2]/div/div/div[2]/div/div[3]/div[3]/ul/li[1]/article/?/?/a[@title>'Apple iPhone 13 512GB (Apple']//header/?/?/h2[@title>'Apple iPhone 13 512GB (Apple']", ".//div[#'__next']//h2[@title>'Apple iPhone 13 512GB (Apple']", 30000, null, "dc99a6b3-03cb-47ec-a915-ecb19aee314a");
                _somesvgtagInfo = new RepoItemInfo(this, "SomeSvgTag", ".//div[#'__next']/main/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/ul/li[1]/article//svg", ".//div[#'__next']//article/div[1]/div/svg", 30000, null, "17981535-7a9a-41aa-9808-7712cfe1e98d");
                _somesvgtag1Info = new RepoItemInfo(this, "SomeSvgTag1", ".//div[#'__next']/main/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/ul/li[2]/article//svg", ".//div[#'__next']/main/div[2]/div[2]/div/div[2]/div/div[3]/div[3]/ul/li[2]/article/div[1]/div/svg", 30000, null, "379a92df-ee5a-4d74-a4b1-36a2e0b4cfe5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b5e8af47-5b31-4617-8936-19add35394e2")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b5e8af47-5b31-4617-8936-19add35394e2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The XiaomiRedmi9T64GBXiaomiTuerkiyeG item.
            /// </summary>
            [RepositoryItem("ac0bed3c-64d9-4e18-85c7-fceea316ddf5")]
            public virtual Ranorex.H2Tag XiaomiRedmi9T64GBXiaomiTuerkiyeG
            {
                get
                {
                    return _xiaomiredmi9t64gbxiaomituerkiyegInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The XiaomiRedmi9T64GBXiaomiTuerkiyeG item info.
            /// </summary>
            [RepositoryItemInfo("ac0bed3c-64d9-4e18-85c7-fceea316ddf5")]
            public virtual RepoItemInfo XiaomiRedmi9T64GBXiaomiTuerkiyeGInfo
            {
                get
                {
                    return _xiaomiredmi9t64gbxiaomituerkiyegInfo;
                }
            }

            /// <summary>
            /// The SueperFiyatlar item.
            /// </summary>
            [RepositoryItem("eb4c045a-a353-4dcb-95ae-e6fd3877c463")]
            public virtual Ranorex.ATag SueperFiyatlar
            {
                get
                {
                    return _sueperfiyatlarInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SueperFiyatlar item info.
            /// </summary>
            [RepositoryItemInfo("eb4c045a-a353-4dcb-95ae-e6fd3877c463")]
            public virtual RepoItemInfo SueperFiyatlarInfo
            {
                get
                {
                    return _sueperfiyatlarInfo;
                }
            }

            /// <summary>
            /// The WalkingpadR1Pro125HpKatlanabilirK item.
            /// </summary>
            [RepositoryItem("2190d1b8-ec2b-4a3e-8b4b-ce7f88a7bb70")]
            public virtual Ranorex.H2Tag WalkingpadR1Pro125HpKatlanabilirK
            {
                get
                {
                    return _walkingpadr1pro125hpkatlanabilirkInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The WalkingpadR1Pro125HpKatlanabilirK item info.
            /// </summary>
            [RepositoryItemInfo("2190d1b8-ec2b-4a3e-8b4b-ce7f88a7bb70")]
            public virtual RepoItemInfo WalkingpadR1Pro125HpKatlanabilirKInfo
            {
                get
                {
                    return _walkingpadr1pro125hpkatlanabilirkInfo;
                }
            }

            /// <summary>
            /// The AddToBasket item.
            /// </summary>
            [RepositoryItem("b80ece62-c474-4d9a-b7f9-854b8281a833")]
            public virtual Ranorex.ButtonTag AddToBasket
            {
                get
                {
                    return _addtobasketInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToBasket item info.
            /// </summary>
            [RepositoryItemInfo("b80ece62-c474-4d9a-b7f9-854b8281a833")]
            public virtual RepoItemInfo AddToBasketInfo
            {
                get
                {
                    return _addtobasketInfo;
                }
            }

            /// <summary>
            /// The SpanTagBUL item.
            /// </summary>
            [RepositoryItem("cea0bca2-6c88-431c-b4d8-e14fb7ac7b65")]
            public virtual Ranorex.SpanTag SpanTagBUL
            {
                get
                {
                    return _spantagbulInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagBUL item info.
            /// </summary>
            [RepositoryItemInfo("cea0bca2-6c88-431c-b4d8-e14fb7ac7b65")]
            public virtual RepoItemInfo SpanTagBULInfo
            {
                get
                {
                    return _spantagbulInfo;
                }
            }

            /// <summary>
            /// The AppleIPhone13512GBAppleTuerkiyeGa item.
            /// </summary>
            [RepositoryItem("dc99a6b3-03cb-47ec-a915-ecb19aee314a")]
            public virtual Ranorex.H2Tag AppleIPhone13512GBAppleTuerkiyeGa
            {
                get
                {
                    return _appleiphone13512gbappletuerkiyegaInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The AppleIPhone13512GBAppleTuerkiyeGa item info.
            /// </summary>
            [RepositoryItemInfo("dc99a6b3-03cb-47ec-a915-ecb19aee314a")]
            public virtual RepoItemInfo AppleIPhone13512GBAppleTuerkiyeGaInfo
            {
                get
                {
                    return _appleiphone13512gbappletuerkiyegaInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag item.
            /// </summary>
            [RepositoryItem("17981535-7a9a-41aa-9808-7712cfe1e98d")]
            public virtual Ranorex.SvgTag SomeSvgTag
            {
                get
                {
                    return _somesvgtagInfo.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag item info.
            /// </summary>
            [RepositoryItemInfo("17981535-7a9a-41aa-9808-7712cfe1e98d")]
            public virtual RepoItemInfo SomeSvgTagInfo
            {
                get
                {
                    return _somesvgtagInfo;
                }
            }

            /// <summary>
            /// The SomeSvgTag1 item.
            /// </summary>
            [RepositoryItem("379a92df-ee5a-4d74-a4b1-36a2e0b4cfe5")]
            public virtual Ranorex.SvgTag SomeSvgTag1
            {
                get
                {
                    return _somesvgtag1Info.CreateAdapter<Ranorex.SvgTag>(true);
                }
            }

            /// <summary>
            /// The SomeSvgTag1 item info.
            /// </summary>
            [RepositoryItemInfo("379a92df-ee5a-4d74-a4b1-36a2e0b4cfe5")]
            public virtual RepoItemInfo SomeSvgTag1Info
            {
                get
                {
                    return _somesvgtag1Info;
                }
            }
        }

        /// <summary>
        /// The GittiGidiyorYardımSayfalarınaHoşgeldiAppFolder folder.
        /// </summary>
        [RepositoryFolder("07a80ede-b8ae-4bf6-b8f8-f96872a27f78")]
        public partial class GittiGidiyorYardımSayfalarınaHoşgeldiAppFolder : RepoGenBaseFolder
        {
            PRJRepositoryFolders.ContainerFolder _container;
            RepoItemInfo _cggarticleInfo;

            /// <summary>
            /// Creates a new GittiGidiyorYardımSayfalarınaHoşgeldi  folder.
            /// </summary>
            public GittiGidiyorYardımSayfalarınaHoşgeldiAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GittiGidiyorYardımSayfalarınaHoşgeldi", "/dom[@domain='yardim.gittigidiyor.net']", parentFolder, 30000, null, false, "07a80ede-b8ae-4bf6-b8f8-f96872a27f78", "")
            {
                _container = new PRJRepositoryFolders.ContainerFolder(this);
                _cggarticleInfo = new RepoItemInfo(this, "CGGArticle", ".//div[#'ggArticleWrapper']/div", ".//div[#'ggArticleWrapper']/div", 30000, null, "f8b4060c-407f-48d7-adf2-4b754e9ddaa3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("07a80ede-b8ae-4bf6-b8f8-f96872a27f78")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("07a80ede-b8ae-4bf6-b8f8-f96872a27f78")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CGGArticle item.
            /// </summary>
            [RepositoryItem("f8b4060c-407f-48d7-adf2-4b754e9ddaa3")]
            public virtual Ranorex.DivTag CGGArticle
            {
                get
                {
                    return _cggarticleInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The CGGArticle item info.
            /// </summary>
            [RepositoryItemInfo("f8b4060c-407f-48d7-adf2-4b754e9ddaa3")]
            public virtual RepoItemInfo CGGArticleInfo
            {
                get
                {
                    return _cggarticleInfo;
                }
            }

            /// <summary>
            /// The Container folder.
            /// </summary>
            [RepositoryFolder("8dee2067-7368-41fd-b2d9-bf7c3999f4b0")]
            public virtual PRJRepositoryFolders.ContainerFolder Container
            {
                get { return _container; }
            }
        }

        /// <summary>
        /// The ContainerFolder folder.
        /// </summary>
        [RepositoryFolder("8dee2067-7368-41fd-b2d9-bf7c3999f4b0")]
        public partial class ContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _lightningprimitiveiconInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _forcecommunitysearchInfo;
            RepoItemInfo _atagbanaulaşmadıneyapmalıyımInfo;

            /// <summary>
            /// Creates a new Container  folder.
            /// </summary>
            public ContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("Container", "body/div[3]/div[2]/div", parentFolder, 30000, null, false, "8dee2067-7368-41fd-b2d9-bf7c3999f4b0", "")
            {
                _lightningprimitiveiconInfo = new RepoItemInfo(this, "LightningPrimitiveIcon", "div/div/div[3]/div/div/div/div/div/div/div/div[1]/?/?/button[@title='Ara']/tag[@tagname='lightning-primitive-icon']", "", 30000, null, "ceb546d1-1336-40f5-9acd-7da72cc5abf3");
                _textInfo = new RepoItemInfo(this, "Text", "div/div/div[3]/div/div/div/div/div/div/div/div[1]/?/?/input[@type='text']", "", 30000, null, "f4706315-07c6-427d-bf45-e2e0bf00bcc5");
                _forcecommunitysearchInfo = new RepoItemInfo(this, "ForceCommunitySearch", "div/div/div[2]/div/div[2]/div/div/div/div[2]/div[2]/ul/li[3]/?/?/p/?/?/a[@innertext>' bana ulaşmadı. Ne yapmal']", "", 30000, null, "a4d8b9d3-b8fc-4ea5-b2c7-2458f04e1115");
                _atagbanaulaşmadıneyapmalıyımInfo = new RepoItemInfo(this, "ATagBanaUlaşmadıNeYapmalıyım", "div[2]/div/div[2]/div/div[2]/div/div/div/div[2]/?/?/ul/li[3]/?/?/p/?/?/a[@innertext>' bana ulaşmadı. Ne yapmal']", "", 30000, null, "9f4742a2-093d-4bda-8fb1-77eec92e4e86");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8dee2067-7368-41fd-b2d9-bf7c3999f4b0")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8dee2067-7368-41fd-b2d9-bf7c3999f4b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LightningPrimitiveIcon item.
            /// </summary>
            [RepositoryItem("ceb546d1-1336-40f5-9acd-7da72cc5abf3")]
            public virtual Ranorex.WebElement LightningPrimitiveIcon
            {
                get
                {
                    return _lightningprimitiveiconInfo.CreateAdapter<Ranorex.WebElement>(true);
                }
            }

            /// <summary>
            /// The LightningPrimitiveIcon item info.
            /// </summary>
            [RepositoryItemInfo("ceb546d1-1336-40f5-9acd-7da72cc5abf3")]
            public virtual RepoItemInfo LightningPrimitiveIconInfo
            {
                get
                {
                    return _lightningprimitiveiconInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("f4706315-07c6-427d-bf45-e2e0bf00bcc5")]
            public virtual Ranorex.InputTag Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("f4706315-07c6-427d-bf45-e2e0bf00bcc5")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The ForceCommunitySearch item.
            /// </summary>
            [RepositoryItem("a4d8b9d3-b8fc-4ea5-b2c7-2458f04e1115")]
            public virtual Ranorex.ATag ForceCommunitySearch
            {
                get
                {
                    return _forcecommunitysearchInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ForceCommunitySearch item info.
            /// </summary>
            [RepositoryItemInfo("a4d8b9d3-b8fc-4ea5-b2c7-2458f04e1115")]
            public virtual RepoItemInfo ForceCommunitySearchInfo
            {
                get
                {
                    return _forcecommunitysearchInfo;
                }
            }

            /// <summary>
            /// The ATagBanaUlaşmadıNeYapmalıyım item.
            /// </summary>
            [RepositoryItem("9f4742a2-093d-4bda-8fb1-77eec92e4e86")]
            public virtual Ranorex.ATag ATagBanaUlaşmadıNeYapmalıyım
            {
                get
                {
                    return _atagbanaulaşmadıneyapmalıyımInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagBanaUlaşmadıNeYapmalıyım item info.
            /// </summary>
            [RepositoryItemInfo("9f4742a2-093d-4bda-8fb1-77eec92e4e86")]
            public virtual RepoItemInfo ATagBanaUlaşmadıNeYapmalıyımInfo
            {
                get
                {
                    return _atagbanaulaşmadıneyapmalıyımInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
