///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PRJ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SSS recording.
    /// </summary>
    [TestModule("80b15e97-edcf-416f-a3f1-a85c6752565d", ModuleType.Recording, 1)]
    public partial class SSS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PRJRepository repository.
        /// </summary>
        public static PRJRepository repo = PRJRepository.Instance;

        static SSS instance = new SSS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SSS()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SSS Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorYardımSayfalarınaHoşgeldi.Container.Text' at 158;22.", repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.TextInfo, new RecordItemIndex(0));
            repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.Text.Click("158;22");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kargo' with focus on 'GittiGidiyorYardımSayfalarınaHoşgeldi.Container.Text'.", repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.TextInfo, new RecordItemIndex(1));
            repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.Text.PressKeys("kargo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorYardımSayfalarınaHoşgeldi.Container.LightningPrimitiveIcon' at 10;1.", repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.LightningPrimitiveIconInfo, new RecordItemIndex(2));
            repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.LightningPrimitiveIcon.Click("10;1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorYardımSayfalarınaHoşgeldi.Container.ForceCommunitySearch' at 114;426.", repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.ForceCommunitySearchInfo, new RecordItemIndex(3));
            repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.ForceCommunitySearch.Click("114;426");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorYardımSayfalarınaHoşgeldi.Container.ATagBanaUlaşmadıNeYapmalıyım' at 109;12.", repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.ATagBanaUlaşmadıNeYapmalıyımInfo, new RecordItemIndex(4));
            repo.GittiGidiyorYardımSayfalarınaHoşgeldi.Container.ATagBanaUlaşmadıNeYapmalıyım.Click("109;12");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
