///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PRJ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyBlankSpaces recording.
    /// </summary>
    [TestModule("0311c850-eebd-4195-9cba-108b9572e883", ModuleType.Recording, 1)]
    public partial class VerifyBlankSpaces : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PRJRepository repository.
        /// </summary>
        public static PRJRepository repo = PRJRepository.Instance;

        static VerifyBlankSpaces instance = new VerifyBlankSpaces();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyBlankSpaces()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyBlankSpaces Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPost.Name' at 67;29.", repo.ApplicationUnderTest.RegisterPost.NameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RegisterPost.Name.Click("67;29");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'ApplicationUnderTest.RegisterPost.Name'.", repo.ApplicationUnderTest.RegisterPost.NameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RegisterPost.Name.PressKeys(" ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPost.Surname' at 86;28.", repo.ApplicationUnderTest.RegisterPost.SurnameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RegisterPost.Surname.Click("86;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'ApplicationUnderTest.RegisterPost.Surname'.", repo.ApplicationUnderTest.RegisterPost.SurnameInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.RegisterPost.Surname.PressKeys(" ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SuggestionEmailInputVerifier' at 107;35.", repo.ApplicationUnderTest.SuggestionEmailInputVerifierInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.SuggestionEmailInputVerifier.Click("107;35");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'ApplicationUnderTest.SuggestionEmailInputVerifier'.", repo.ApplicationUnderTest.SuggestionEmailInputVerifierInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.SuggestionEmailInputVerifier.PressKeys(" ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PwdField' at 93;33.", repo.ApplicationUnderTest.PwdFieldInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.PwdField.Click("93;33");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'ApplicationUnderTest.PwdField'.", repo.ApplicationUnderTest.PwdFieldInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.PwdField.PressKeys(" ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GsmData' at 89;32.", repo.ApplicationUnderTest.GsmDataInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.GsmData.Click("89;32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ' with focus on 'ApplicationUnderTest.GsmData'.", repo.ApplicationUnderTest.GsmDataInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.GsmData.PressKeys(" ");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubmitForm' at 138;34.", repo.ApplicationUnderTest.SubmitFormInfo, new RecordItemIndex(10));
            repo.ApplicationUnderTest.SubmitForm.Click("138;34");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
