///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PRJ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifySpecifiedFields recording.
    /// </summary>
    [TestModule("0d4b1fc9-2074-4cdc-8106-fa96f0b15c46", ModuleType.Recording, 1)]
    public partial class VerifySpecifiedFields : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PRJRepository repository.
        /// </summary>
        public static PRJRepository repo = PRJRepository.Instance;

        static VerifySpecifiedFields instance = new VerifySpecifiedFields();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifySpecifiedFields()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifySpecifiedFields Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown.Name' at 58;24.", repo.Dropdown.NameInfo, new RecordItemIndex(0));
            repo.Dropdown.Name.Click("58;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown.Surname' at 53;28.", repo.Dropdown.SurnameInfo, new RecordItemIndex(1));
            repo.Dropdown.Surname.Click("53;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SuggestionEmailInputVerifier' at 58;25.", repo.ApplicationUnderTest.SuggestionEmailInputVerifierInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SuggestionEmailInputVerifier.Click("58;25");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.PwdField' at 56;27.", repo.ApplicationUnderTest.PwdFieldInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.PwdField.Click("56;27");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.GsmData' at 79;31.", repo.ApplicationUnderTest.GsmDataInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.GsmData.Click("79;31");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPost.Checkmark' at 11;10.", repo.ApplicationUnderTest.RegisterPost.CheckmarkInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.RegisterPost.Checkmark.Click("11;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPost.Checkmark' at 11;10.", repo.ApplicationUnderTest.RegisterPost.CheckmarkInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.RegisterPost.Checkmark.Click("11;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RegisterPost.Checkmark' at 11;10.", repo.ApplicationUnderTest.RegisterPost.CheckmarkInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.RegisterPost.Checkmark.Click("11;10");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
