///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PRJ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyAddToWishlist recording.
    /// </summary>
    [TestModule("364b22ec-e056-49b9-91e0-5a67baf5ddf0", ModuleType.Recording, 1)]
    public partial class VerifyAddToWishlist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PRJRepository repository.
        /// </summary>
        public static PRJRepository repo = PRJRepository.Instance;

        static VerifyAddToWishlist instance = new VerifyAddToWishlist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyAddToWishlist()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyAddToWishlist Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown.InputTagK' at 106;24.", repo.Dropdown.InputTagKInfo, new RecordItemIndex(0));
            repo.Dropdown.InputTagK.Click("106;24");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ipad' with focus on 'Dropdown.InputTagK'.", repo.Dropdown.InputTagKInfo, new RecordItemIndex(1));
            repo.Dropdown.InputTagK.PressKeys("ipad");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorTuerkiyeninOEncueAlışve2.SpanTagBUL' at 26;9.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SpanTagBULInfo, new RecordItemIndex(2));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SpanTagBUL.Click("26;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(3));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorTuerkiyeninOEncueAlışve2.SomeSvgTag' at 14;10.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SomeSvgTagInfo, new RecordItemIndex(4));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SomeSvgTag.Click("14;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorTuerkiyeninOEncueAlışve2.SomeSvgTag1' at 15;11.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SomeSvgTag1Info, new RecordItemIndex(5));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SomeSvgTag1.Click("15;11");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
