///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PRJ
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The VerifyAddToCart recording.
    /// </summary>
    [TestModule("059a059f-55ad-4104-bf7f-5545954ec9c1", ModuleType.Recording, 1)]
    public partial class VerifyAddToCart : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PRJRepository repository.
        /// </summary>
        public static PRJRepository repo = PRJRepository.Instance;

        static VerifyAddToCart instance = new VerifyAddToCart();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public VerifyAddToCart()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static VerifyAddToCart Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown.InputTagK' at 85;19.", repo.Dropdown.InputTagKInfo, new RecordItemIndex(0));
            repo.Dropdown.InputTagK.Click("85;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'iphone 13' with focus on 'Dropdown.InputTagK'.", repo.Dropdown.InputTagKInfo, new RecordItemIndex(1));
            repo.Dropdown.InputTagK.PressKeys("iphone 13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorTuerkiyeninOEncueAlışve2.SpanTagBUL' at 18;7.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SpanTagBULInfo, new RecordItemIndex(2));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.SpanTagBUL.Click("18;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'GittiGidiyorTuerkiyeninOEncueAlışve2.AppleIPhone13512GBAppleTuerkiyeGa' at 112;12.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.AppleIPhone13512GBAppleTuerkiyeGaInfo, new RecordItemIndex(3));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.AppleIPhone13512GBAppleTuerkiyeGa.MoveTo("112;12");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'GittiGidiyorTuerkiyeninOEncueAlışve2.AppleIPhone13512GBAppleTuerkiyeGa' at 130;9.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.AppleIPhone13512GBAppleTuerkiyeGaInfo, new RecordItemIndex(4));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.AppleIPhone13512GBAppleTuerkiyeGa.MoveTo("130;9");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GittiGidiyorTuerkiyeninOEncueAlışve2.AddToBasket' at 148;27.", repo.GittiGidiyorTuerkiyeninOEncueAlışve2.AddToBasketInfo, new RecordItemIndex(5));
            repo.GittiGidiyorTuerkiyeninOEncueAlışve2.AddToBasket.Click("148;27");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
